### ISSUE TITLE
The game's crashlogs are being reported as they were on a server.

### ISSUE THREAD

**Issue by KirbyKid256** [skylorbeck/Sentimentality3#12]
Hi, so I'm trying to use as many mods as I can in Minecraft, so there would definitely be some incompatibilities anyways, but my game keeps crashing when I go to a certain area. It also gives me crash reports like I'm on a server when I'm in singleplayer. I don't know what the problem is, but I was hoping you can help.
[crash-2021-08-18_08.30.09-server.txt](https://github.com/Skylortrexler/Sentimentality3/files/7007248/crash-2021-08-18_08.30.09-server.txt)

**Comment by skylorbeck** [comment]
Looks like it has something to do with Patchouli or a mod that uses it. Good luck!
