### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by efffauw** [skylorbeck/Sentimentality3#15]
Crashing on startup 
[log](https://pastebin.com/TfpsnAqN)

**Comment by skylorbeck** [comment]
"[22:07:33] [ForkJoinPool-1-worker-2/WARN]: The mod "wolveswitharmor" contains invalid entries in its mod json:
- Unsupported root entry "artist" at line 15 column 11
[22:07:33] [main/WARN]: Warnings were found!
 - Mod 'Custom Entity Models' (cem) 0.7.0 recommends any version of completeconfig, which is missing!
	 - You should install any version of completeconfig for the optimal experience."On Jan 4, 2022 6:13 AM, efffauw ***@***.***> wrote:
Crashing on startup
log
