### ISSUE TITLE
Vanilla Recipes

### ISSUE THREAD

**Issue by SHXRKIEgg** [skylorbeck/Sentimentality3#16]
Hi, your mod adds additional recipes for Vanilla Recipes like Stairs or Trapdoors etc, would it be possible to add a config to disable it?

**Comment by skylorbeck** [comment]
Absolutely. Will continue to work on this.

**Comment by skylorbeck** [comment]
Alright I made the serializer and now I just have to make 600+ recipes work with it lol

**Comment by skylorbeck** [comment]
I actually removed the vanilla stair/door recipes as I didn't like them that much to begin with. If the outcry is large I'll readd them with config settings
