### ISSUE TITLE
Crash on startup on fabric 1.18.1

### ISSUE THREAD

**Issue by Zano1999** [skylorbeck/Sentimentality3#18]
log: https://pastebin.com/b4dM3Zqw

**Comment by skylorbeck** [comment]
[00:57:41] [ForkJoinPool-1-worker-2/WARN]: The mod "libcd" contains invalid entries in its mod json

**Comment by Zano1999** [comment]
That line on libcd appears every time, even without your mod and the game works fine, I also tried to remove it but it doesn't change anything, by the way libcd is a mod that is automatically installed with other mods

**Comment by skylorbeck** [comment]
Oh you have clean-cut installed. Sentimentality provides the same thing and as thus, is incompatible.
