### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by YnwLNE** [skylorbeck/Sentimentality3#19]
Gives exit code: 1 when installed so a crash log isn't given. Hopefully this latest log can help. GJ on the mod though! (and the others you've made) 
Fabric: 13.3
Version 1.18.1

https://pastebin.com/EbZ97gJL

**Comment by skylorbeck** [comment]
The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column

Go talk to them.

**Comment by YnwLNE** [comment]
Will do, ty
