### ISSUE TITLE
Configuration not working consistently 

### ISSUE THREAD

**Issue by Samarai** [skylorbeck/Sentimentality3#3]
A large amount of the toggleable settings don't seem to work as intended, most evident with settings like disabling additional tool types and/or compressed blocks. Neither individual toggles nor the global toggles for these features disable the items or their recipes. 

Just to ensure it wasn't an issue with the in-game Mod Menu, I checked the configuration file, and any changed settings were saved as intended. If needed, I can do more specific testing of which settings do and don't function, as a few do work properly.

**Comment by skylorbeck** [comment]
Looks like I accidentally moved the config to load after all the items are loaded while updating to 1.17. Thanks for the heads up.
