### ISSUE TITLE
Possible Incompatibility with EarlyGame

### ISSUE THREAD

**Issue by Samarai** [skylorbeck/Sentimentality3#4]
Ever since the recent update fixing Issue 3, all pickaxes and axes are seemingly not being recognized as such by EarlyGame [https://www.curseforge.com/minecraft/mc-mods/earlygame](url)
This includes vanilla tools, tools added by Sentimentality 3, and tools added by EarlyGame. In practice, this means that axes (and EG's saws) can't cut wood and can't turn logs into planks, and pickaxes can't cut stone. The easiest way to see this in action is to enable EG's warnings for trying to harvest wood without an axe/stone without a pickaxe, they'll appear even when holding the correct tool.

**Comment by skylorbeck** [comment]
It sounds like Early Game might have issues with tooltags added by Fabric
