### ISSUE TITLE
Feature request. Stone tools actually made from the stone, not cobblestone.

### ISSUE THREAD

**Issue by K0-RR** [skylorbeck/Sentimentality3#7]
There are datapacks with this, I know.
Just change crafting recipes of stone tools to be made out of the stone blocks instead of the cobblestone. Why? Because the texture obviously looks like stone, not cobble.

**Comment by skylorbeck** [comment]
You're not wrong.

**Comment by skylorbeck** [comment]
I just added the recipes, you can still craft with cobblestone if you wanted but I like having the option

**Comment by K0-RR** [comment]
Thanks!
