### ISSUE TITLE
Conflicts with FallingTree Mod

### ISSUE THREAD

**Issue by Veldimare** [skylorbeck/Sentimentality3#9]
Mod conflicts with FallingTree mod in some way.

When installed the mod doesn't work correctly, but as far as I can tell it's not throwing any errors.

**Comment by skylorbeck** [comment]
Are you sure it's my mod? I'm playing with both in my world right now. What version of fallingtree are you using?

**Comment by Veldimare** [comment]
Really.. Okay..

If I remove your mod, it works correctly, so I was assuming that's where the conflict happened.

Currently installed - FallingTree-1.17.1-2.12.3
Also tried with 2.11.4
Sentimentality3 Version = 1.2.9

I do have a modified config..
[sentimentality3.zip](https://github.com/Skylortrexler/Sentimentality3/files/6971078/sentimentality3.zip)

(allTools = false + individuals, allCompressedBlocks = false + individuals, chunker, charcoal, coalChunks, Sticks, FeatherBlock, Gliders, Furnaces, Blasts, Smokers, WoolArmor, CopperArmor = false)

**Comment by skylorbeck** [comment]
Oh I see. I wonder if the problem is because you have my tools disabled, and my tools try to register with the fabric tool tags, which I assume fallingtree uses too. Let me do some testing and see if thats the cause.

**Comment by skylorbeck** [comment]
Yes this is the problem. Fabric fails to load tool tags completely if a mod attempts to add a non-existing tool to the tag list. Thank you for the report, I'll be working on this asap.

**Comment by Veldimare** [comment]
No problem at all!
Glad you were able to figure it out!

**Comment by skylorbeck** [comment]
It looks like this is both a problem with Sentimentality and FallingTree. In 1.17, minecraft added a tool tag system and neither of us used it in our 1.17 updates. I have solved my half, which fixed FallingTree not working, but now my Axes no longer work with FT. FT will have to update to use the new system before my axes work again. I'll push this update later this week to give time for FT to update as well as put some more fixes in S3.
